export default function Privacy() {
  return (
    <div className="max-w-4xl mx-auto py-12 px-4 sm:px-6 lg:px-8">
      <h1 className="page-title">Privacy Policy for Pour Decisions</h1>

      <div className="card prose prose-invert max-w-none">
        <div className="space-y-6 text-white opacity-90">
          <p className="text-lg">Last updated: April 07, 2025</p>

          <section className="space-y-4">
            <h2 className="text-2xl font-bold text-primary-pink">
              Privacy Policy
            </h2>
            <p>
              This Privacy Policy describes Our policies and procedures on the
              collection, use, and disclosure of Your information when You use
              the Service and tells You about Your privacy rights and how the
              law protects You.
            </p>
            <p>
              We use Your Personal data to provide and improve the Service. By
              using the Service, You agree to the collection and use of
              information in accordance with this Privacy Policy. This Privacy
              Policy has been created with the help of the Free Privacy Policy
              Generator.
            </p>
          </section>

          <section className="space-y-4">
            <h2 className="text-2xl font-bold text-primary-pink">
              Interpretation and Definitions
            </h2>
            <h3 className="text-xl font-semibold">Interpretation</h3>
            <p>
              The words of which the initial letter is capitalized have meanings
              defined under the following conditions. The following definitions
              shall have the same meaning regardless of whether they appear in
              singular or in plural.
            </p>
            <h3 className="text-xl font-semibold">Definitions</h3>
            <p>For the purposes of this Privacy Policy:</p>
            <ul className="list-disc pl-6 space-y-2">
              <li>
                <strong>Account:</strong> A unique account created for You to
                access our Service or parts of our Service.
              </li>
              <li>
                <strong>Affiliate:</strong> An entity that controls, is
                controlled by, or is under common control with a party, where
                "control" means ownership of 50% or more of the shares, equity
                interest, or other securities entitled to vote for election of
                directors or other managing authority.
              </li>
              <li>
                <strong>Application:</strong> Refers to Pour Decisions, the
                software program provided by the Company.
              </li>
              <li>
                <strong>Company:</strong> Refers to CSIBI FILIP PERSOANA FIZICA
                AUTORIZATA, Aleea PANSELUŢELOR, Nr. 3, Bl. 27, Scara B, Ap. 15.
              </li>
              <li>
                <strong>Country:</strong> Refers to Romania.
              </li>
              <li>
                <strong>Device:</strong> Any device that can access the Service
                such as a computer, a cellphone, or a digital tablet.
              </li>
              <li>
                <strong>Personal Data:</strong> Any information that relates to
                an identified or identifiable individual.
              </li>
              <li>
                <strong>Service:</strong> Refers to the Application.
              </li>
              <li>
                <strong>Service Provider:</strong> Any natural or legal person
                who processes the data on behalf of the Company. It refers to
                third-party companies or individuals employed by the Company to
                facilitate the Service, provide the Service on behalf of the
                Company, perform services related to the Service, or assist the
                Company in analyzing how the Service is used.
              </li>
              <li>
                <strong>Usage Data:</strong> Data collected automatically,
                either generated by the use of the Service or from the Service
                infrastructure itself (for example, the duration of a page
                visit).
              </li>
              <li>
                <strong>You:</strong> The individual accessing or using the
                Service, or the company, or other legal entity on behalf of
                which such individual is accessing or using the Service, as
                applicable.
              </li>
            </ul>
          </section>

          <section className="space-y-4">
            <h2 className="text-2xl font-bold text-primary-pink">
              Collecting and Using Your Personal Data
            </h2>
            <h3 className="text-xl font-semibold">Types of Data Collected</h3>
            <h4 className="text-lg font-medium">Personal Data</h4>
            <p>
              While using Our Service, We may ask You to provide Us with certain
              personally identifiable information that can be used to contact or
              identify You. Personally identifiable information may include, but
              is not limited to:
            </p>
            <ul className="list-disc pl-6 space-y-2">
              <li>Usage Data</li>
            </ul>
            <h4 className="text-lg font-medium">Usage Data</h4>
            <p>
              Usage Data is collected automatically when using the Service. This
              may include information such as Your Device's Internet Protocol
              address (e.g., IP address), browser type, browser version, the
              pages of our Service that You visit, the time and date of Your
              visit, the time spent on those pages, unique device identifiers,
              and other diagnostic data.
            </p>
            <p>
              When You access the Service by or through a mobile device, We may
              collect certain information automatically, including, but not
              limited to, the type of mobile device You use, Your mobile device
              unique ID, the IP address of Your mobile device, Your mobile
              operating system, the type of mobile Internet browser You use,
              unique device identifiers, and other diagnostic data.
            </p>
          </section>

          <section className="space-y-4">
            <h2 className="text-2xl font-bold text-primary-pink">
              Use of Your Personal Data
            </h2>
            <p>The Company may use Personal Data for the following purposes:</p>
            <ul className="list-disc pl-6 space-y-2">
              <li>To provide and maintain our Service</li>
              <li>To manage Your Account</li>
              <li>To contact You</li>
              <li>To manage Your requests</li>
              <li>For business transfers</li>
              <li>
                For other purposes such as data analysis and improving the
                Service
              </li>
            </ul>
          </section>

          <section className="space-y-4">
            <h2 className="text-2xl font-bold text-primary-pink">
              Disclosure of Your Personal Data
            </h2>
            <p>
              The Company may disclose Your Personal Data in the good faith
              belief that such action is necessary to:
            </p>
            <ul className="list-disc pl-6 space-y-2">
              <li>Comply with a legal obligation</li>
              <li>Protect and defend the rights or property of the Company</li>
              <li>Prevent or investigate possible wrongdoing</li>
              <li>Protect against legal liability</li>
            </ul>
          </section>

          <section className="space-y-4">
            <h2 className="text-2xl font-bold text-primary-pink">Contact Us</h2>
            <p>
              If you have any questions about this Privacy Policy, You can
              contact us:
            </p>
            <p className="font-medium text-primary-pink">
              By email: csibifilip777@gmail.com
            </p>
          </section>
        </div>
      </div>
    </div>
  );
}
